version: "3"
services:
  ibro_samples:
    image: coltspb/ibro-samples
    container_name: ibro_samples
    hostname: ibro_samples
    restart: always
    environment:
      - MODE=PRODUCTION
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ibro_samples.rule=Host(`ibro.best`)"
      - "traefik.http.routers.ibro_samples.entrypoints=websecure"
      - "traefik.http.routers.ibro_samples.tls.certresolver=leresolver"
      
      - "traefik.http.routers.ibro_samples_http.rule=Host(`ibro.best`)"
      - "traefik.http.routers.ibro_samples_http.entrypoints=web"
    networks:
      - frontend

      
networks:
  frontend:
    external: true
    
  
