name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./scripts/test.sh


  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: coltspb 
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build
      run: |
        docker-compose -f deploy/docker-compose.yml -f deploy/build.yml build
        docker-compose -f deploy/docker-compose.yml -f deploy/build.yml push
    
    - name: Setup SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
    - name: Deploy
      run: |
        ssh root@deploy.ibro.best 'mkdir -p /opt/ibro-samples && cd /opt/ibro-samples && if [ -e "docker-compose.yml" ]; then docker-compose down; fi'
        scp -r deploy/* root@deploy.ibro.best:/opt/ibro-samples
        ssh root@deploy.ibro.best GITHUB_SHA=$GITHUB_SHA /opt/ibro-samples/deploy.sh
