name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test master
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./scripts/test.sh


  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    needs: test

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    
    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: coltspb 
        password: ${{ secrets.DOCKER_TOKEN }}
    
    - name: Build
      run: |
        docker-compose -f deploy.yml build
        docker-compose -f deploy.yml push
    
    - name: Setup SSH
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        name: id_rsa
        known_hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      
    - name: Deploy
      run: |
        ssh root@deploy.ibro.best 'mkdir -p /opt/ibro-samples'
        scp deploy.yml root@deploy.ibro.best:/opt/ibro-samples/docker-compose.yml
        ssh root@deploy.ibro.best 'cd /opt/ibro-samples && docker-compose pull && docker-compose down && docker-compose up -d'
