name: Docker

on:
  # Run tests for any PRs.
  pull_request:
    branches: 
      - master

jobs:
  test:
    name: Test PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: ./scripts/test.sh
